# Generated by Django 5.2.8 on 2025-12-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_group_user_alter_link_group_alter_link_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.CharField(help_text="URL of the link", max_length=2000),
        ),
    ]
