# Generated by Django 5.2.8 on 2026-02-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="last_accessed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
