"""
Django settings for linkman project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()


def get_env_var(env_var: str) -> str:
    """
    Gets a specified environment variable.
    :param env_var: Name of the environment variable
    :return: The value of the specified environment variable
    """
    value = os.getenv(env_var)
    if value is None:
        error_message = f"Set the {env_var} environment variable!"
        raise ImproperlyConfigured(error_message)
    return value


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_var("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
# IN PROD DO THIS -> ALLOWED_HOSTS = ["Your IP", "Your Domain"]


# Application definition
MY_APPS: list[str] = ["apps.authentication", "apps.main", "apps.api"]
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_browser_reload",
    "tailwind",
    "theme",
    *MY_APPS,
]

# Tell django-tailwind which app contains your Tailwind code
TAILWIND_APP_NAME = "theme"

# Enable development mode (auto rebuild)
TAILWIND_DEV_MODE = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Session Configuration
SESSION_ENGINE = (
    "django.contrib.sessions.backends.db"  # Store the session in the Database
)
SESSION_COOKIE_AGE: int = (
    60 * 60 * 24 * 7 * 2
)  # Cookie length stored in seconds (2 Weeks Here)
SESSION_COOKIE_HTTPONLY: bool = True
SESSION_COOKIE_NAME: str = "sessionid"
SESSION_COOKIE_SAMESITE: str = "Lax"

# IMPORTANT: Ensure these values are uncommented and properly set in production
# SESSION_COOKIE_SECURE: bool = True

# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#
# CSRF_TRUSTED_ORIGINS = [
#     '',
#     ''
# ]
# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
LOGIN_URL: str = "login_page"
LOGOUT_REDIRECT_URL: str = "landing_page"

# EMAIL CONFIGURATION
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = get_env_var("EMAIL_NAME")
EMAIL_HOST_PASSWORD = get_env_var("APP_PASSWORD")
EMAIL_PORT = 587

ROOT_URLCONF = "linkman.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",  # templates folder(s)
        ],
        "APP_DIRS": True,  # Also look in app directories
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "linkman.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_env_var("DB_NAME"),
        "USER": get_env_var("DB_USER"),
        "PASSWORD": get_env_var("DB_PASSWORD"),
        "HOST": get_env_var("DB_HOST"),
        "PORT": get_env_var("DB_PORT"),
    }
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # server port/location
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,
                "retry_on_timeout": True,
            },
        },
    }
}
# CUSTOM USER
AUTH_USER_MODEL = "authentication.CustomUser"

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static"  # global static folder
]
# STATIC_ROOT = "/home/ubuntu/[insert appname]/staticfiles/"  # for production (via collectstatic)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
